\
"""
ON3RT Radio Suite
Module Logbook
ADIF Export Manager
"""

from pathlib import Path
from typing import Iterable


class ExportManager:
    """Exporte une collection de QSO au format ADIF."""

    def export(self, qsos: Iterable, filename: str) -> int:
        path = Path(filename)

        with path.open("w", encoding="utf-8", newline="\n") as f:
            f.write("Generated by ON3RT Radio Suite\n")
            f.write("<ADIF_VER:5>3.1.4\n")
            f.write("<PROGRAMID:17>ON3RT Radio Suite\n")
            f.write("<EOH>\n\n")

            count = 0

            for qso in qsos:
                fields = self._to_dict(qso)

                for key, value in fields.items():
                    if value is None:
                        continue
                    value = str(value)
                    if value == "":
                        continue
                    f.write(f"<{key}:{len(value)}>{value}\n")

                f.write("<EOR>\n\n")
                count += 1

        return count

    def _to_dict(self, qso):
        if hasattr(qso, "__dict__"):
            return {
                k.upper(): v
                for k, v in vars(qso).items()
                if not k.startswith("_")
            }

        if isinstance(qso, dict):
            return {k.upper(): v for k, v in qso.items()}

        raise TypeError("Unsupported QSO object")
